# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'SO',
                'verbose_name_plural': 'Sistemas Operativos',
            },
        ),
        migrations.CreateModel(
            name='SubCapitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('comandos', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Capitulo')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SistemaOperativo')),
            ],
            options={
                'verbose_name': 'Sub-Capitulo',
                'verbose_name_plural': 'Sub-Capitulo',
            },
        ),
        migrations.AddField(
            model_name='capitulo',
            name='sistema_operativo',
            field=models.ManyToManyField(to='app.SistemaOperativo'),
        ),
    ]
