# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-12 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AlterModelOptions(
            name='sistemaoperativo',
            options={'verbose_name': 'Sistema Operativo', 'verbose_name_plural': 'Sistemas Operativos'},
        ),
        migrations.AlterModelOptions(
            name='subcapitulo',
            options={'verbose_name': 'Sub-Capítulo', 'verbose_name_plural': 'Sub-Capítulos'},
        ),
        migrations.RemoveField(
            model_name='subcapitulo',
            name='sistema_operativo',
        ),
        migrations.AddField(
            model_name='subcapitulo',
            name='sistema_operativo',
            field=models.ManyToManyField(blank=True, to='app.SistemaOperativo'),
        ),
    ]
